# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Backend CI

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: server

jobs:
  build:

    runs-on: [self-hosted, linux]

    strategy:
      matrix:
        node-version: [20.x]
        typesense-version: [0.25.2]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
        path: ~/.cache/firebase/emulators
    - name: Typesense Server in GitHub Actions
      uses: jirevwe/typesense-github-action@v1.0.1
      with:
        typesense-version: ${{ matrix.typesense-version }}
        typesense-api-key: test-key
    - run: npm ci
    - run: npm install -g firebase-tools
    - run: npm run build --if-present
    - name: test
      run: npm test
      env:
        TYPESENSE_API_KEY: test-key
